# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3f0fcb8b40c312bc5b08f9391824f58b2f2aba3c2309b14ad0ad62c15441035b2eea12c665d3781d57ff71c117e6a4c1e0da3f345d6f432fa8d2881a5947930

test:
  secret_key_base: 2e1143b05986409fd20faceb833c2062420d5b3149763b79929246df24ab218a625a470df553cb5a826c02bb3f46aef85f8e2fba770f781f4c25724fd36a6fd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
